[package]
name = "lupe"
version = "0.1.1"
edition = "2021"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
comfy-table = "7.2.1"
duckdb = { version = "1.4.2", features = ["bundled"] }
hyper-util = "0.1.18"
prost = "0.14.1"
tokio = { version = "1.48.0", default-features = false, features = ["rt", "rt-multi-thread", "macros", "signal", "process"] }
tonic = "0.14.2"
tonic-prost = "0.14.2"
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
typed-builder = "0.23.2"

[target.'cfg(windows)'.dependencies]
async-stream = "0.3.6"
futures-core = "0.3.31"
windows = { version = "0.58.0", features = ["Win32"] }

[build-dependencies]
tonic-prost-build = "0.14.2"
