[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
]

[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static-libstdc++",
    "-C", "link-arg=-static-libgcc",
    "-C", "link-arg=-static",
]
